### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by vaeng** [comment]
Hahaha, this is madness. I love it.

**Comment by vaeng** [comment]
It is indeed, please ping me, if you are at a stage to implement exercises. I would love to add some.

**Comment by ErikSchierboom** [comment]
We're set: https://github.com/exercism/uiua/pull/4! 

I've opened https://github.com/exercism/uiua-test-runner/issues/2 to allow us to claim exercises we want to build.

Note: I am a total n00b in array programming, especially with the tacit approach Uiua has. The language itself is also very new to me, so please let me know of anything you'd like me to change.

**Comment by SleeplessByte** [comment]
⍤⤙≍⍤⤙≍⍤⤙≍⍤⤙≍⍤⤙≍⍤⤙≍⍤⤙≍

**Pull request merged**
